#!/usr/bin/env python3
"""Generate Terminal's TilFeatureStaging.h without PowerShell or MSBuild."""

from __future__ import annotations

import argparse
import fnmatch
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path


NAMESPACE = "http://microsoft.com/TilFeatureStaging-Schema.xsd"
NS = {"til": NAMESPACE}
VALID_NAME = re.compile(r"^Feature_[A-Za-z0-9_]+$")
VALID_STAGES = {"AlwaysDisabled", "AlwaysEnabled"}
VALID_BRANDINGS = {"Dev", "Canary", "Preview", "Release", "WindowsInbox"}


@dataclass(frozen=True)
class Feature:
    name: str
    stage: str
    branch_stages: dict[str, str] = field(default_factory=dict)
    branding_stages: dict[str, str] = field(default_factory=dict)
    disabled_for_release: bool = False

    @property
    def preprocessor_name(self) -> str:
        return f"TIL_{self.name.upper()}_ENABLED"


def child_text(element: ET.Element, name: str) -> str:
    child = element.find(f"til:{name}", NS)
    if child is None or child.text is None:
        raise ValueError(f"feature is missing required {name}")
    return child.text.strip()


def token_stages(element: ET.Element, disabled_path: str, enabled_path: str) -> dict[str, str]:
    stages: dict[str, str] = {}
    for token in element.findall(disabled_path, NS):
        if token.text:
            stages[token.text.strip()] = "AlwaysDisabled"
    # Match the upstream generator: enabled entries override disabled entries.
    for token in element.findall(enabled_path, NS):
        if token.text:
            stages[token.text.strip()] = "AlwaysEnabled"
    return stages


def parse_features(path: Path) -> list[Feature]:
    root = ET.parse(path).getroot()
    if root.tag != f"{{{NAMESPACE}}}featureStaging":
        raise ValueError(f"unexpected root element: {root.tag}")

    features: list[Feature] = []
    names: set[str] = set()
    for element in root.findall("til:feature", NS):
        name = child_text(element, "name")
        stage = child_text(element, "stage")
        if not VALID_NAME.fullmatch(name):
            raise ValueError(f"invalid feature name: {name}")
        if name in names:
            raise ValueError(f"duplicate feature name: {name}")
        if stage not in VALID_STAGES:
            raise ValueError(f"invalid stage for {name}: {stage}")
        names.add(name)
        features.append(
            Feature(
                name=name,
                stage=stage,
                branch_stages=token_stages(
                    element,
                    "til:alwaysDisabledBranchTokens/til:branchToken",
                    "til:alwaysEnabledBranchTokens/til:branchToken",
                ),
                branding_stages=token_stages(
                    element,
                    "til:alwaysDisabledBrandingTokens/til:brandingToken",
                    "til:alwaysEnabledBrandingTokens/til:brandingToken",
                ),
                disabled_for_release=element.find("til:alwaysDisabledReleaseTokens", NS)
                is not None,
            )
        )
    return sorted(features, key=lambda feature: feature.name)


def resolve_stage(feature: Feature, branding: str, branch: str) -> str:
    if branding in {"Release", "WindowsInbox"} and feature.disabled_for_release:
        return "AlwaysDisabled"

    matches = [
        (pattern, stage)
        for pattern, stage in feature.branch_stages.items()
        if fnmatch.fnmatchcase(branch.casefold(), pattern.casefold())
    ]
    if matches:
        return max(matches, key=lambda item: len(item[0]))[1]
    return feature.branding_stages.get(branding, feature.stage)


def render(features: list[Feature], branding: str, branch: str, input_label: str) -> str:
    lines = [
        "// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT IT",
        f"// INPUT FILE: {input_label}",
        "#pragma once",
        "",
    ]
    final_stages: dict[str, str] = {}
    for feature in features:
        final_stage = resolve_stage(feature, branding, branch)
        final_stages[feature.name] = final_stage
        enabled = "1" if final_stage == "AlwaysEnabled" else "0"
        lines.extend((f"#define {feature.preprocessor_name} {enabled}", ""))

    lines.extend(("#if defined(__cplusplus)", ""))
    for feature in features:
        lines.extend(
            (
                f'__pragma(detect_mismatch("ODR_violation_{feature.preprocessor_name}_mismatch", "{feature.stage}"))',
                f"struct {feature.name}",
                "{",
                f"    static constexpr bool IsEnabled() {{ return {feature.preprocessor_name} == 1; }}",
                "};",
                "",
            )
        )
    lines.extend(("#endif", ""))
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("features_xml", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--branding", choices=sorted(VALID_BRANDINGS), default="Dev")
    parser.add_argument("--branch", default="")
    parser.add_argument("--input-label", default="src/features.xml")
    args = parser.parse_args()

    features = parse_features(args.features_xml)
    write_if_changed(
        args.output,
        render(features, args.branding, args.branch, args.input_label),
    )


if __name__ == "__main__":
    main()
