#!/usr/bin/env python3
"""Emit an `E_NOTIMPL` base class for each WinRT interface the DLL implements.

A WinRT interface is pure virtual in its entirety: `IUIElement` alone declares
96 methods, and a class cannot be instantiated until every one of them exists.
Almost all of them are irrelevant to layout -- events, brushes, transforms,
automation -- but they still have to be present, and in the right vtable slot.

Transcribing 200-odd signatures by hand is the failure mode this avoids. A
method typed in the wrong order does not fail to build; it silently shifts
every later slot, and the caller invokes the wrong function through a
correctly-typed pointer. Deriving the stubs from the SDK header means the
vtable order is the SDK's, not ours.

The generated bases leave `IInspectable`'s own six methods pure, because those
belong to the object rather than to any one interface and are implemented once
by the object itself.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

INTERFACE = re.compile(r"^\s+(?P<name>I\w+) : public IInspectable\s*$", re.M)
END = re.compile(r"^\s+\};\s*$", re.M)
METHOD = re.compile(r"virtual HRESULT STDMETHODCALLTYPE (?P<name>\w+)\(", re.S)

# Implemented by the object, not by any single interface.
INSPECTABLE = {"QueryInterface", "AddRef", "Release",
               "GetIids", "GetRuntimeClassName", "GetTrustLevel"}


def split_params(text: str) -> list[str]:
    """Split an argument list on commas that are not inside brackets."""
    out, depth, current = [], 0, ""
    for ch in text:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(current)
            current = ""
            continue
        current += ch
    if current.strip():
        out.append(current)
    return [p.strip() for p in out if p.strip()]


def param_type(param: str) -> str:
    """Drop the parameter name, keeping the type.

    The declaration is always `TYPE name`, with `*` and `&` bound to the type
    in the SDK's generated style, so the name is the trailing identifier.
    """
    param = " ".join(param.split())
    match = re.match(r"^(?P<type>.*?[\s*&])(?P<name>\w+)$", param)
    return (match.group("type") if match else param).strip()


def parse_interface(text: str, start: int) -> list[tuple[str, list[str]]]:
    end = END.search(text, start)
    body = text[start:end.start()] if end else text[start:]
    methods = []
    for match in METHOD.finditer(body):
        depth, index = 1, match.end()
        while index < len(body) and depth:
            if body[index] == "(":
                depth += 1
            elif body[index] == ")":
                depth -= 1
            index += 1
        params = [param_type(p) for p in split_params(body[match.end():index - 1])]
        methods.append((match.group("name"), params))
    return methods


def find_interfaces(headers: list[Path], wanted: set[str]) -> dict[str, tuple[str, list]]:
    found: dict[str, tuple[str, list]] = {}
    for path in sorted(headers):
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in INTERFACE.finditer(text):
            name = match.group("name")
            if name not in wanted or name in found:
                continue
            found[name] = (path.name, parse_interface(text, match.end()))
    return found


def emit(order: list[str], qualified: dict[str, str],
         found: dict[str, tuple[str, list]]) -> str:
    lines = [
        "// Generated by phase3/scripts/generate_abi_stubs.py. Do not edit.",
        "//",
        "// One base class per WinRT interface, every method answering E_NOTIMPL.",
        "// An implementation overrides only what it actually supports, so what is",
        "// missing stays visibly missing instead of quietly returning zero.",
        "",
        "#ifndef OPENXAML_GENERATED_ABI_STUBS_H",
        "#define OPENXAML_GENERATED_ABI_STUBS_H",
        "",
        "namespace openxaml::abi {",
        "",
    ]
    for name in order:
        header, methods = found[name]
        full = qualified[name]
        lines.append(f"// {full} -- {len(methods)} methods, from {header}")
        lines.append(f"struct NotImpl_{name} : {full} {{")
        for method, params in methods:
            if method in INSPECTABLE:
                continue
            args = ", ".join(params)
            lines.append(
                f"    HRESULT STDMETHODCALLTYPE {method}({args}) override {{ "
                f"::openxaml::winrt::TraceRuntime(\"OpenXaml: E_NOTIMPL "
                f"{name}.{method}\\n\"); return E_NOTIMPL; }}"
            )
        lines.append("};")
        lines.append("")
    lines += ["}  // namespace openxaml::abi", "", "#endif", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--include-dir", type=Path, required=True)
    parser.add_argument("--interfaces", type=Path, required=True,
                        help="one fully qualified ABI interface name per line")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    qualified = {}
    order = []
    for line in args.interfaces.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        short = line.rsplit("::", 1)[-1]
        qualified[short] = line
        order.append(short)

    headers = sorted(args.include_dir.glob("[Ww]indows.[Uu][Ii].[Xx]aml*.h"))
    colors_header = args.include_dir / "windows.ui.h"
    if colors_header.is_file():
        headers.append(colors_header)
    text_header = args.include_dir / "windows.ui.text.h"
    if text_header.is_file():
        headers.append(text_header)
    for adjacent in ("windows.foundation.h", "windows.system.h",
                     "windows.applicationmodel.resources.core.h",
                     "windows.ui.viewmanagement.h",
                     # The thread's CoreWindow, which a XAML island owns.
                     "windows.ui.core.h"):
        header = args.include_dir / adjacent
        if header.is_file():
            headers.append(header)
    found = find_interfaces(headers, set(order))
    missing = [n for n in order if n not in found]
    if missing:
        raise SystemExit("not found in the SDK headers: " + ", ".join(missing))

    text = emit(order, qualified, found)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != text:
        args.output.write_text(text, encoding="utf-8")
    total = sum(len(m) for _, m in found.values())
    print(f"{len(order)} interfaces, {total} methods stubbed")


if __name__ == "__main__":
    main()
