// XAML measurement harness.
//
// Reads case files, realises each one's markup with XamlReader::Load, runs the
// layout contract against the case's available size, and writes the resulting
// tree out as JSON. This is the oracle: it needs the real Windows.UI.Xaml,
// which is part of Windows and exists nowhere else, so CI runs it on
// windows-latest.
//
// One binary serves the whole corpus. Cases are markup strings loaded at
// runtime, so adding a case never means compiling anything.

#include <winrt/base.h>
#include <winrt/Windows.Foundation.h>
// Ranged-for over a WinRT collection (Panel::Children) needs this: the
// Foundation header only *declares* IIterable's begin/end, and they return
// auto, so iterating without the definitions is a hard error.
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.System.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Media.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Hosting.h>

#include <windows.h>
#include <dispatcherqueue.h>

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using namespace winrt;
using namespace Windows::UI::Xaml;

namespace {

// --- minimal JSON reading -----------------------------------------------------
// The case format is generated by our own script and is deliberately flat, so a
// full parser would be more machinery than the input warrants.
std::string slurp(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

std::string json_unescape(const std::string& s) {
    std::string out;
    for (size_t i = 0; i < s.size(); ++i) {
        if (s[i] != '\\') { out += s[i]; continue; }
        if (++i >= s.size()) break;
        switch (s[i]) {
            case 'n': out += '\n'; break;
            case 't': out += '\t'; break;
            case 'r': out += '\r'; break;
            case 'u': {
                // Only the BMP escapes our generator can emit.
                if (i + 4 < s.size()) {
                    int cp = std::stoi(s.substr(i + 1, 4), nullptr, 16);
                    if (cp < 0x80) out += static_cast<char>(cp);
                    i += 4;
                }
                break;
            }
            default: out += s[i];
        }
    }
    return out;
}

std::optional<std::string> string_field(const std::string& doc, const std::string& key) {
    auto k = "\"" + key + "\"";
    auto at = doc.find(k);
    if (at == std::string::npos) return std::nullopt;
    at = doc.find(':', at + k.size());
    if (at == std::string::npos) return std::nullopt;
    auto open = doc.find('"', at);
    if (open == std::string::npos) return std::nullopt;
    std::string out;
    for (size_t i = open + 1; i < doc.size(); ++i) {
        if (doc[i] == '\\') { out += doc[i]; out += doc[i + 1]; ++i; continue; }
        if (doc[i] == '"') break;
        out += doc[i];
    }
    return json_unescape(out);
}

// available_size is [x, y] where either may be the string "Infinity", because
// JSON cannot spell infinity and a bare token would not be portable.
std::pair<float, float> available_size(const std::string& doc) {
    auto at = doc.find("\"available_size\"");
    if (at == std::string::npos) return {400.f, 300.f};
    auto open = doc.find('[', at);
    auto close = doc.find(']', open);
    auto body = doc.substr(open + 1, close - open - 1);
    std::vector<float> vals;
    std::string tok;
    std::istringstream ts(body);
    while (std::getline(ts, tok, ',')) {
        auto b = tok.find_first_not_of(" \t\r\n\"");
        auto e = tok.find_last_not_of(" \t\r\n\"");
        if (b == std::string::npos) continue;
        auto v = tok.substr(b, e - b + 1);
        vals.push_back(v == "Infinity" ? std::numeric_limits<float>::infinity()
                                       : std::stof(v));
    }
    if (vals.size() < 2) return {400.f, 300.f};
    return {vals[0], vals[1]};
}

// --- JSON writing -------------------------------------------------------------
std::string esc(const std::string& s) {
    std::string o;
    for (char c : s) {
        if (c == '"' || c == '\\') { o += '\\'; o += c; }
        else if (c == '\n') o += "\\n";
        else o += c;
    }
    return o;
}

// Layout values are floats but must compare byte-for-byte across runs, so they
// are emitted at fixed precision rather than with the shortest round trip.
std::string num(double v) {
    if (std::isinf(v)) return "\"Infinity\"";
    if (std::isnan(v)) return "\"NaN\"";
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(4) << v;
    return ss.str();
}

std::string type_name(const DependencyObject& o) {
    return to_string(get_class_name(o));
}

// --- tree walk ----------------------------------------------------------------
// Both halves of the contract are recorded. An implementation can arrange the
// right final rect while measuring wrongly; that only surfaces once the element
// sits under a panel that consults DesiredSize, so DesiredSize is recorded too.
void walk(const UIElement& el, const std::string& path, std::ostringstream& out, bool& first) {
    if (!first) out << ",\n";
    first = false;

    auto desired = el.DesiredSize();
    double aw = 0, ah = 0, ox = 0, oy = 0;
    if (auto fe = el.try_as<FrameworkElement>()) {
        aw = fe.ActualWidth();
        ah = fe.ActualHeight();
        // The slot the parent arranged this element into. TransformToVisual
        // would need the element to be in a live visual tree, and these trees
        // are measured detached -- they are never shown on screen.
        auto slot = Controls::Primitives::LayoutInformation::GetLayoutSlot(fe);
        ox = slot.X;
        oy = slot.Y;
    }

    out << "  {\"path\": \"" << esc(path) << "\""
        << ", \"type\": \"" << esc(type_name(el)) << "\""
        << ", \"desired\": [" << num(desired.Width) << ", " << num(desired.Height) << "]"
        << ", \"actual\": [" << num(aw) << ", " << num(ah) << "]"
        << ", \"offset\": [" << num(ox) << ", " << num(oy) << "]}";

    int i = 0;
    if (auto panel = el.try_as<Controls::Panel>()) {
        for (auto&& child : panel.Children()) {
            walk(child, path + "/" + type_name(child) + "[" + std::to_string(i++) + "]", out, first);
        }
    } else if (auto border = el.try_as<Controls::Border>()) {
        if (auto c = border.Child()) walk(c, path + "/" + type_name(c) + "[0]", out, first);
    } else if (auto cc = el.try_as<Controls::ContentControl>()) {
        if (auto c = cc.Content().try_as<UIElement>())
            walk(c, path + "/" + type_name(c) + "[0]", out, first);
    }
}

}  // namespace

int wmain(int argc, wchar_t** argv) {
    if (argc < 3) {
        std::wcerr << L"usage: xaml_probe <cases-dir> <out-dir>\n";
        return 2;
    }
    fs::path cases = argv[1], outdir = argv[2];

    // Both of these have to outlive every measurement: releasing the queue
    // controller takes the thread's DispatcherQueue down with it, and
    // dropping the manager shuts XAML down.
    com_ptr<::IUnknown> queue;
    Hosting::WindowsXamlManager manager{nullptr};

    // Bringing XAML up is the one part of this program that cannot be tried
    // anywhere but a real Windows machine, so name the step that failed
    // rather than dying as an unhandled exception.
    try {
        init_apartment(apartment_type::single_threaded);

        // XAML needs a DispatcherQueue on the thread before it will
        // initialise; WindowsXamlManager throws without one. The WinRT
        // projection can only create a controller on a *dedicated* thread, so
        // the queue for this thread comes from the CoreMessaging entry point.
        DispatcherQueueOptions options{sizeof(DispatcherQueueOptions),
                                       DQTYPE_THREAD_CURRENT, DQTAT_COM_STA};
        check_hresult(CreateDispatcherQueueController(
            options, reinterpret_cast<PDISPATCHERQUEUECONTROLLER*>(queue.put())));

        manager = Hosting::WindowsXamlManager::InitializeForCurrentThread();
    } catch (hresult_error const& e) {
        std::cerr << "cannot start XAML: " << to_string(e.message())
                  << " (hresult 0x" << std::hex << static_cast<uint32_t>(e.code()) << ")\n";
        return 3;
    }

    fs::create_directories(outdir);
    int ok = 0, failed = 0;

    std::vector<fs::path> files;
    for (auto& e : fs::recursive_directory_iterator(cases))
        if (e.path().extension() == L".json") files.push_back(e.path());
    std::sort(files.begin(), files.end());  // stable order, byte-stable output

    for (auto& f : files) {
        auto doc = slurp(f);
        auto id = string_field(doc, "id").value_or(f.stem().string());
        auto markup = string_field(doc, "markup");
        if (!markup) { ++failed; std::cerr << id << ": no markup\n"; continue; }
        auto [aw, ah] = available_size(doc);

        std::ostringstream tree;
        std::string error;
        bool first = true;
        try {
            auto obj = Markup::XamlReader::Load(to_hstring(*markup));
            auto el = obj.as<UIElement>();
            el.Measure({aw, ah});
            auto d = el.DesiredSize();
            // Arrange against the available size where it is finite; an infinite
            // final rect is not a legal arrange input, so fall back to desired.
            el.Arrange({0, 0,
                        std::isinf(aw) ? d.Width : aw,
                        std::isinf(ah) ? d.Height : ah});
            walk(el, "/" + type_name(el), tree, first);
        } catch (hresult_error const& e) {
            error = to_string(e.message());
        }

        std::ostringstream o;
        o << "{\n \"schema_version\": 1,\n \"case_id\": \"" << esc(id) << "\",\n";
        if (!error.empty()) {
            o << " \"error\": \"" << esc(error) << "\"\n}\n";
            ++failed;
        } else {
            o << " \"tree\": [\n" << tree.str() << "\n ]\n}\n";
            ++ok;
        }
        std::ofstream(outdir / (id + ".json"), std::ios::binary) << o.str();
    }

    std::cout << ok << " measured, " << failed << " failed\n";
    return failed ? 1 : 0;
}
