// A small JSON reader, enough for the case files and no more.
//
// The case corpus is generated by our own script, so this could get away with
// scanning for quoted substrings -- but a case that silently parses wrong
// produces a plausible measurement rather than an error, and that is exactly
// the failure this whole database exists to make impossible.

#ifndef OPENXAML_JSON_H
#define OPENXAML_JSON_H

#include <map>
#include <stdexcept>
#include <string>
#include <vector>

namespace openxaml {

class JsonValue {
public:
    enum class Kind { Null, Bool, Number, String, Array, Object };

    Kind kind = Kind::Null;
    bool boolean = false;
    double number = 0.0;
    std::string string;
    std::vector<JsonValue> array;
    std::map<std::string, JsonValue> object;

    bool Has(const std::string& key) const { return object.count(key) != 0; }
    const JsonValue& At(const std::string& key) const;
};

class JsonError : public std::runtime_error {
public:
    explicit JsonError(const std::string& what) : std::runtime_error(what) {}
};

JsonValue ParseJson(const std::string& text);

// Escapes a string for emission. Only the escapes the writer can actually
// produce; the corpus has no control characters beyond newline.
std::string JsonEscape(const std::string& s);

}  // namespace openxaml

#endif  // OPENXAML_JSON_H
